name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: npm install

      - run: npm run build
